version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build:
      context: labsite
    depends_on:
      - db
    ports:
      - '8000:8000'
volumes:
  db:
    driver: local
